name: Publish

on:
  push:
    branches:
      - cf-pages

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        include:
          - projectName: 'sandpack-landing'
            path: website/landing
            NEXT_PUBLIC_AMPLITUDE_API_KEY: a205ed9b06a7baf5a594bdd30293aa80
            buildCommand: cd website/landing && yarn build:deps && npx @cloudflare/next-on-pages --experimental-minify
          - projectName: 'sandpack-docs'
            path: website/docs
            NEXT_PUBLIC_AMPLITUDE_API_KEY: a205ed9b06a7baf5a594bdd30293aa80
            buildCommand: yarn build && cd website/docs && npx @cloudflare/next-on-pages --experimental-minify
          - projectName: 'sandpack-theme'
            path: website/theme
            NEXT_PUBLIC_AMPLITUDE_API_KEY: a205ed9b06a7baf5a594bdd30293aa80
            buildCommand: cd website/theme && yarn build:deps && npx @cloudflare/next-on-pages --experimental-minify

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile --silent

      - name: Run build
        run: ${{ matrix.buildCommand }}
        env:
          NEXT_PUBLIC_AMPLITUDE_API_KEY: ${{ matrix.NEXT_PUBLIC_AMPLITUDE_API_KEY }}

      - name: Publish
        uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 0e922dabe6dbbcdecdb3a09dca5bbd55
          projectName: ${{ matrix.projectName }}
          directory: ${{ matrix.path }}/.vercel/output/static
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
